set -g default-shell /usr/local/bin/fish
set -g default-terminal "screen-256color"

set -g history-limit 10000

# Remove timeout after pressing escape.
set -s escape-time 0

# Enable mouse mode.
set -g mouse on

# Enable vim-style keys.
set-window-option -g mode-keys vi
unbind -T copy-mode-vi Space
unbind -T copy-mode-vi Enter
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "pbcopy"

unbind r
bind r source-file ~/.tmux.conf \; display "Reloaded config"

unbind s
bind s set-window-option synchronize-panes
