theme = "catppuccin_mocha"

[editor]
mouse = true

[editor.cursor-shape]
insert = "bar"

[editor.lsp]
display-inlay-hints = true

[editor.whitespace.render]
space = "all"
tab = "all"

[editor.whitespace.characters]
space = "·"
tab = "→"
